# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration


client_id = "db3941abd1f634665d3a402ddfddb6a3"
name = "Animated Character Badges"
handle = "animated-character-badges"
application_url = "https://oyster-app-fhr34.ondigitalocean.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "poc-v2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://oyster-app-fhr34.ondigitalocean.app/auth/callback",
  "https://oyster-app-fhr34.ondigitalocean.app/auth/shopify/callback",
  "https://oyster-app-fhr34.ondigitalocean.app/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
